language: node_js
node_js:
- node
install:
- npm install
env:
  global:
  - GH_REF: github.com/MaterialDev/Thread
  - secure: GdbVmodiQe8+VTHYs1iwYNe7pVO8ATUGAk9Mbj4caCJS8n4zPRCMa3Ua3GIKZHXqlRNUyvHZXu5iFZC+lwOqCm2muFDZD5WjlDR3sHkwTZR9EvodqgwtpfL0ZyvIRcagd0vyGYMUiYifRXp7V75/A+e64C7V4+eMmjtnGOIWcGdW8grbEgDgdur5z70SeAHTlNmNnTZYleqA2t4MlC7nc7E3J/54MctE3ndYRzWGuH5/KmxC3ODjruwZGqq+xP0yLZL9SerG31tu4rqMZ8ThXzxWjtVUlyfxGohvvfzUaWvffjsv1wACKRPFqjR7iD/ET6j83kfe1CEEuxKVCUYgSx4JpAafWZEWXUNeLJ6YK83fA3pFIb8uUo5I8DhVXWkSMLnV+AiOWI11udrem5FfRHfnQIOqDWam8Tpgs2Ij50cfU53lStdL4pmLJpXBpUdKPXyLx1nh4O8bJGgN0PFfWUtkkdBxZC/L+oiM8AbMCCxhb7VIU9mbGjOYW1Mcd9ICv87tH0IRhNZJdAv/QkGF+Xqg9KjIclur85YCwXebkuN8SG3QOPr2BJO3k2voeRoCSeVKdQnIeTwSBGjNkNDSBJsbSpj+son85VwgymQVwRXIe61QvrDlWTuUPnLk35Lsp+/bg+CPrJpzkhw+b/OpR6Oni13H1m9CGtyXR/xzfDU=
before_script:
- npm install -g gulp
script:
- gulp build
after_success:
- bash deploy.sh
cache:
- node_modules
- bower_components
branches:
  only:
  - master
