language: node_js
node_js:
- node
install:
- npm install
env:
  global:
  - GH_REF: github.com/MaterialDev/Thread
  - secure: fr3r4wvURVlwtewBJ8+ZgTJFEJR0rdFQbnZcdFjQg12bQGVSfqVDxnpNjmOhRiRtc9TDpc/NprBCgzP1ryaMN/p7LFJT/MEHg++VkM/vgCeph1L9BPbDGqQdOKDfqLellptAu1agzDFL4KvBbiPbubx1bnNuDf9LEaXVSVMJwckW6OIywRoUg1lzWGHQCyvEsZ5LoJAsBjFaIxarOJSuzRaQwMzcDROkXqnaNlinqSoihmz/mQG3G7Hg9+zTdL9+G6sYFRCKjCKtenr2Jk0AdDE819YJUt0nn8Psrf2q4RUPjFgcVxwXo0oJlOoHxKjqSMeLjph5ucz5nrVYPlPEsxsgtQRYY7Zfkbq55swp3+0UNmz3edyCcD2FItaDR50KryMycIyhF3h46xBSlIa/zRAZHghTYyVJdgtxEd1GS3SS+fegFKbB4Hgl04Y3znmJXVWpAqvJRax0BI3VKfoU89HvXgkY26GnLkqr86rJaE/lSos+Z+UP4CtvQe26/iChyes+3nyT+cpCxOIq+d0t0KJKhU2y7r2sSNMmYDHUedb+d2tya8ryYIR9REEEs340OWKE+pLOX5gXEDGbAbRYXsH9hYjMsJG/3WTjU1aXZ3Tf6U/TgNGqBWs5kwYkCmllIAqBCA4TE9lDU1iLqJrWSrdlixWJWEAt0wwgqJrTCyo=
before_script:
- npm install -g gulp
script:
- gulp build
after_success:
- bash deploy.sh
cache:
  - node_modules
  - bower_components
branches:
  only:
    - master
